name: Generate Snake Animation

on:
  schedule: # run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: abrar898
          outputs: dist/snake.svg

      - name: Push generated snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
